### ISSUE TITLE
How is your filter as positional parameter to your inventory script working?

### ISSUE THREAD

**Issue by refriedjello** [tkjaer/ansible-dynamic-inventory#1]
In your readme you have this example of using this script:

> $ ansible -i ./ansible-dynamic-inventory.py dsw* --list

Indicating that you can pass a filter (dsw*) as the first positional argument to your inventory script. I cannot find where in your code this is being handled.

Is your code really able to perform selective dynamic queries like that from your CMDB? I don't have LibreNMS to test this code out, but am very interested in pulling only certain hosts from my CMDB using wildcard matches like that. Versus pulling all or just one, which appears to be the case in every other example I can find.

Thanks!

**Comment by tkjaer** [comment]
Hi @refriedjello,

The pattern matching is done by ansible.  The arguments in the above example are for ansible itself, and `dsw*` is ansibles `<host-pattern>` argument.

As per the [Ansible guide for development of dynamic inventory scripts](https://docs.ansible.com/ansible/devel/dev_guide/developing_inventory.html), the only two arguments ansible will pass to the script are `--list` and `--host <hostname>`.

In the given example ansible requests the full inventory from the dynamic inventory and then filters out the host pattern itself.

/Thomas

**Comment by refriedjello** [comment]
I see, thank you for the answer!
